// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for LivelinkFunction
 */
export interface LivelinkFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/livelink.
 */
export class LivelinkFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: LivelinkFunctionProps) {
    super(scope, id, {
      description: 'src/livelink.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/livelink.lambda')),
    });
  }
}